### ISSUE TITLE
Auto-publish docker image

### ISSUE THREAD

**Issue by pi0neerpat** [open-dollar/od-app#212]
Depends on #24

Automatically build and publish the docker container

- Every merge to main branch
- On manual dispatch, which creates a release-candidate version tag of the current git commit 
- Publish to github public registry (you may need to choose another since you may not have permissions to publish to our organization directly)
- Version should match what's in package.json
- update the docker-compose to pull from the GitHub registry without needing any extra configuration for the end-user.

**Comment by IsmaelTerreno** [comment]
### Potential plan to use

Based on the changes in this [PR](https://github.com/open-dollar/od-app/pull/207), the plan is to supplement this workflow using [GitActions](https://docs.github.com/en/actions) so we can translate this into steps so we can have a CD/CI devOps file in ".github" with a "workflow" folder with a file called **open-dollar-app-pipeline.yml** to use in Github.

So in the case:

> Every merge to main branch

We can add as trigger: 
```
on:
    push:
        branches:
            - dev
```

In the case of : 

> On manual dispatch, which creates a release-candidate version tag of the current git commit

We can use a job like:

```
jobs:
    deploy:
         name: Deploy open dollar app
         runs-on: ubuntu-latest
         steps:
            -   name: Build, tag, and push image to registry
                 id: build-image
                 # Env vars are used in the Dockerfile
                 env:
                    ECR_REGISTRY: XXXX
                    ECR_REPOSITORY: XXXX
                    IMAGE_TAG: XXXX # Here we can use latest or calculate the image tag name
         run: |
                    docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
                    docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
                    echo "{image}={$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG}" >> $GITHUB_OUTPUT
```
But of course is a draft this is only to give an idea of the job to run on GitActions.

In the case of:

> Publish to github public registry (you may need to choose another since you may not have permissions to publish to our organization directly)

I think we can use public registries like Github and Docker Hub 

In the case of :  

> Version should match what's in package.json

Maybe we ca consider adding a step in the job to calculate this before the build.

In the case of: 

> update the docker-compose to pull from the GitHub registry without needing any extra configuration for the end-user.

We can reuse and refactor if needed the docker compose file from this [PR](https://github.com/open-dollar/od-app/pull/207) so that the user can avoid extra configuration.

Again this is only a draft idea but I think it makes sense for a starting point.
